enum COLOR_CODE {
  WINE_RED = '#722f37',
  LIGHT_SKY_BLUE = 'lightskyblue',
  SKY_BLUE = '#87CEEB',
  WHITE = 'white',
  LIGHT_GREY = '#D3D3D3',
  BLACK = '#000000',
  OFF_WHITE = '#FAF9F6',
  SHADOW_COLOR = '#171717',
  BRIGHT_BLUE = '#0096FF',
  BRIGHT_RED = '#FF4255',
  GREY = 'grey',
  GREEN = '#0F9D58',
  LIGHT_SILVER = '#e5eeef',
  FIRE_YELLOW = '#FEDE17',
  FIRE_GREEN = '#00D100',
  FIRE_PURPLE = '#800080',
  FIRE_SILVER = '#C0C0C0',
  FIRE_BLUE = '#3D88FF',
  RED = 'red',
  GOLDEN = '#FFD700',
  DIM_GREY = '#dadada',
  LOGO_COLOR = '#7f7fd5',
  LOGO_BLUE = '#86A8E7'
}

enum ERROR_CODES {
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',

  VALIDATION_ERROR = 'VALIDATION_ERROR',

  TOKEN_NOT_SUPPLIED = 'TOKEN_NOT_SUPPLIED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_TOKEN_PARAMS = 'INVALID_TOKEN_PARAMS',

  INVALID_EMAIL = 'INVALID_EMAIL',

  OTP_RESEND_LIMIT = 'OTP_RESEND_LIMIT',
  OTP_VALIDATION_ATTEMPTS_LIMIT = 'OTP_VALIDATION_ATTEMPTS_LIMIT',
  OTP_INVALID = 'OTP_INVALID',

  CITY_NOT_FOUND = 'CITY_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  NUMBER_NOT_FOUND = 'NUMBER_NOT_FOUND',

  DUPLICATE_USER = 'DUPLICATE_USER',
  CONLFIC_USER_NAME = 'CONLFIC_USER_NAME',

  INTERNAL_SERVER = 'INTERNAL_SERVER',
}

enum ChatSocketEvents {
  SAVE_MESSAGE = 'save-message',
  SAVE_FILE = 'save-file',
  MARK_MESSAGES_AS_READ = 'mark-messages-as-read',
  MESSAGE_RECEIVED = 'message-received'
}

export { COLOR_CODE, ERROR_CODES, ChatSocketEvents }